title: Ken Freeman
# your name (or website title) here
logo: "/images/IMG-1677.jpg?raw=true/" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  Currently studying for my Masters in Business Analytics
  with a focus in  Security Analytics at the University
  of Colorado Boulder.
  <br><br> 
  4 years of Logistics and Operations experience in addition
  to 2+ years of managerial experience. I am studying to expand
  my Python, SQL and R skills sets to transition into a more
  data focused role.  <br><br>
  <a href="https://www.linkedin.com/in/kenneth-freeman-analyst">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
